import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "../components/Header";
import ReduxProvider from "./provider";
import {NextIntlClientProvider, useMessages} from 'next-intl';

const inter = Inter({ subsets: ["latin"] });


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, params: {locale} }) {
  const messages = useMessages();
  return (
    <html lang={locale}>
      <body className={inter.className}>
        <ReduxProvider>
        <NextIntlClientProvider messages={messages}>
          <Header />
          {children}
          </NextIntlClientProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
